name: Build misc-utils With Maven

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build Artefact
    runs-on: ubuntu-latest
    steps:

      # Set up Java Temurin 21 (Java 21)
      - name: Set up Java Temurin 21
        uses: actions/setup-java@v2
        with:
          java-package: 'jdk'
          java-version: '21'
          distribution: 'temurin'
          architecture: 'x64'

      # Checkout the repository
      - name: Check out repository code
        uses: actions/checkout@master

      # Cache Maven dependencies to speed up builds
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven build command
      - name: Build with Maven
        run: mvn clean compile package verify

      # Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: misc-utils
          path: target/misc-utils-*.jar
          if-no-files-found: error
          overwrite: true
